### ISSUE TITLE
File does not exist: datalanguagesv850.slaspec

### ISSUE THREAD

**Issue by brandonros** [esaulenka/ghidra_v850#13]
```
$ pwd
/Users/brandonros/Downloads/ghidra_9.1.1_PUBLIC/Extensions/ghidra_v850
$ ../../support/sleigh data\languages\v850.slaspec
Java HotSpot(TM) 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must not be set
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
INFO  Using log config file: jar:file:/Users/brandonros/Downloads/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /Users/brandonros/.ghidra/.ghidra_9.1.1_PUBLIC/application.log (LoggingInitialization)  
ERROR Unrecoverable error(s), halting compilation (SleighCompile) ghidra.sleigh.grammar.BailoutException: input file "datalanguagesv850.slaspec" is not properly case dependent: File does not exist: /Users/brandonros/Downloads/ghidra_9.1.1_PUBLIC/Extensions/ghidra_v850/datalanguagesv850.slaspec
	at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.run_compilation(SleighCompileLauncher.java:351)
	at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.runMain(SleighCompileLauncher.java:277)
	at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.launch(SleighCompileLauncher.java:74)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:79)

```

**Comment by brandonros** [comment]
`../../support/sleigh data/languages/v850.slaspec `

that fixed it lol
